"""High-level skill options compiled into fixed low-level actions."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from ..models import Action, ActionKind, Decision, RobotState


class SkillOption(str, Enum):
    INSPECT_ROOM = "inspect_room"
    MOVE_CLOSER = "move_closer"
    ASK_USER = "ask_user"
    TURN_AC = "turn_ac"
    ALARM = "alarm"
    WAIT = "wait"


@dataclass(frozen=True, slots=True)
class OptionStep:
    """One manager decision; parameters are still untrusted proposals."""

    option: SkillOption
    parameters: dict[str, Any] = field(default_factory=dict)
    reason: str = ""


@dataclass(frozen=True, slots=True)
class HighLevelPlan:
    steps: tuple[OptionStep, ...]
    response: str | None = None
    rationale: str = ""


@dataclass(frozen=True, slots=True)
class OptionDefinition:
    """Options abstraction O=(I, pi, beta) without claiming learned HRL."""

    option: SkillOption
    initiation: str
    fixed_policy: str
    termination: str


OPTION_DEFINITIONS = {
    SkillOption.INSPECT_ROOM: OptionDefinition(
        SkillOption.INSPECT_ROOM,
        "camera available",
        "fixed camera capture and YOLO/VLM pipeline",
        "one structured scene observation produced",
    ),
    SkillOption.MOVE_CLOSER: OptionDefinition(
        SkillOption.MOVE_CLOSER,
        "navigation has fresh obstacle state",
        "fixed navigation controller and motor PID",
        "target distance reached or obstacle/timeout",
    ),
    SkillOption.ASK_USER: OptionDefinition(
        SkillOption.ASK_USER,
        "question is required to resolve ambiguity",
        "fixed TTS/ASR turn-taking pipeline",
        "answer, cancellation, or turn timeout",
    ),
    SkillOption.TURN_AC: OptionDefinition(
        SkillOption.TURN_AC,
        "climate adapter available and target proposed",
        "fixed IR/Home Assistant adapter",
        "device feedback confirms target or timeout",
    ),
    SkillOption.ALARM: OptionDefinition(
        SkillOption.ALARM,
        "valid alarm time proposed",
        "fixed alarm scheduler",
        "alarm persisted or validation failed",
    ),
    SkillOption.WAIT: OptionDefinition(
        SkillOption.WAIT,
        "waiting is preferable to unsafe guessing",
        "no actuator command",
        "next event or deadline",
    ),
}


class FixedOptionCompiler:
    """Translate manager-selected options; low-level policy is never generated by the LLM."""

    def __init__(self, *, max_steps: int = 1, approach_speed: float = 0.25) -> None:
        if max_steps < 1:
            raise ValueError("max_steps must be positive")
        if not 0 < approach_speed <= 1:
            raise ValueError("approach_speed must be within 0..1")
        self.max_steps = max_steps
        self.approach_speed = approach_speed

    def compile(self, plan: HighLevelPlan, state: RobotState) -> Decision:
        if len(plan.steps) > self.max_steps:
            raise ValueError(f"plan exceeds maximum of {self.max_steps} option steps")
        actions: list[Action] = []
        for step in plan.steps:
            action = self._compile_step(step, state)
            if action is not None:
                actions.append(action)
        return Decision(
            tuple(actions),
            plan.response,
            plan.rationale,
            {
                "planning_level": "high_level_skill_options",
                "low_level_control": "fixed",
                "skill_options": [step.option.value for step in plan.steps],
            },
        )

    def _compile_step(self, step: OptionStep, state: RobotState) -> Action | None:
        del state  # Initiation state is enforced by SafetyPolicy after compilation.
        parameters = step.parameters
        requested_by = "embodied_planner_manager"
        if step.option is SkillOption.WAIT:
            return None
        if step.option is SkillOption.INSPECT_ROOM:
            return Action(
                ActionKind.INSPECT_ROOM,
                {"mode": str(parameters.get("mode", "safety"))},
                step.reason or "inspect current room state",
                requested_by,
            )
        if step.option is SkillOption.MOVE_CLOSER:
            return Action(
                ActionKind.MOVE,
                {
                    "direction": "forward",
                    "speed": self.approach_speed,
                    "distance_m": _positive_number(parameters.get("distance_m", 0.5), "distance_m"),
                },
                step.reason or "approach target with fixed navigation controller",
                requested_by,
            )
        if step.option is SkillOption.ASK_USER:
            question = str(parameters.get("question", "请告诉我更多信息。")).strip()
            return Action(ActionKind.SPEAK, {"text": question}, step.reason or "resolve ambiguity", requested_by)
        if step.option is SkillOption.TURN_AC:
            target_c = _number(parameters.get("target_c"), "target_c")
            return Action(
                ActionKind.SET_HVAC,
                {"target_c": target_c},
                step.reason or "adjust thermal comfort",
                requested_by,
            )
        if step.option is SkillOption.ALARM:
            alarm_time = str(parameters.get("time", "")).strip()
            if not alarm_time:
                raise ValueError("alarm option requires time")
            return Action(
                ActionKind.SET_ALARM,
                {"time": alarm_time, "message": str(parameters.get("message", "时间到了。"))},
                step.reason or "schedule user reminder",
                requested_by,
            )
        raise ValueError(f"unsupported skill option: {step.option}")


def _number(value: Any, name: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{name} must be numeric")
    return float(value)


def _positive_number(value: Any, name: str) -> float:
    result = _number(value, name)
    if result <= 0:
        raise ValueError(f"{name} must be positive")
    return result
